import ships, { IPureShip } from "./models/ship";

(async () => {
    await Promise.all(
        ([
            {
                name: "cruiser",
                cost: 50,
                class: "BATTLESHIP",
                description: "A standard ship.",
                health: 100,
                maxHealth: 100,
                level: 1,
                maxLevel: 12,
                levelRequired: 0,
                speed: 20,
                weapons: {
                    heavies: [],
                    heavySlots: 0,
                    mediums: [],
                    mediumSlots: 1,
                    lights: [],
                    lightSlots: 2,
                },
            },
            {
                name: "speeder",
                cost: 150,
                class: "CRUISER",
                description: "Super fast and light.",
                health: 80,
                maxHealth: 80,
                level: 1,
                maxLevel: 12,
                levelRequired: 2,
                speed: 40,
                weapons: {
                    heavies: [],
                    heavySlots: 0,
                    mediums: [],
                    mediumSlots: 0,
                    lights: [],
                    lightSlots: 2,
                },
            },
            {
                name: "shredder",
                cost: 300,
                class: "DESTROYER",
                description: "Good firepower and speed.",
                health: 120,
                maxHealth: 120,
                level: 1,
                maxLevel: 12,
                levelRequired: 5,
                speed: 25,
                weapons: {
                    heavies: [],
                    heavySlots: 1,
                    mediums: [],
                    mediumSlots: 2,
                    lights: [],
                    lightSlots: 0,
                },
            },
            {
                name: "pulsar",
                cost: 350,
                class: "BATTLESHIP",
                description: "Light but durable.",
                health: 160,
                maxHealth: 160,
                level: 1,
                maxLevel: 15,
                levelRequired: 8,
                speed: 22,
                weapons: {
                    heavies: [],
                    heavySlots: 0,
                    mediums: [],
                    mediumSlots: 0,
                    lights: [],
                    lightSlots: 4,
                },
            },
            {
                name: "hospitality",
                cost: 400,
                class: "FRIGATE",
                description: "Supportive ship with decent firepower.",
                health: 140,
                maxHealth: 140,
                level: 1,
                maxLevel: 15,
                levelRequired: 12,
                speed: 30,
                weapons: {
                    heavies: [],
                    heavySlots: 1,
                    mediums: [],
                    mediumSlots: 0,
                    lights: [],
                    lightSlots: 1,
                },
            },
            {
                name: "abyss",
                cost: 500,
                class: "CARRIER",
                description: "A small but speedy carrier.",
                health: 140,
                maxHealth: 140,
                level: 1,
                maxLevel: 20,
                levelRequired: 15,
                speed: 35,
                weapons: {
                    heavies: [],
                    heavySlots: 2,
                    mediums: [],
                    mediumSlots: 0,
                    lights: [],
                    lightSlots: 0,
                },
            },
            {
                name: "uboat",
                cost: 500,
                class: "SUBMARINE",
                description: "*unterseeboot intensifies*",
                health: 140,
                maxHealth: 140,
                level: 1,
                maxLevel: 20,
                levelRequired: 15,
                speed: 35,
                weapons: {
                    heavies: [],
                    heavySlots: 2,
                    mediums: [],
                    mediumSlots: 0,
                    lights: [],
                    lightSlots: 0,
                },
            },
        ] as IPureShip[]).map(
            ({
                name,
                cost,
                class: _class,
                description,
                health,
                levelRequired,
                speed,
                weapons,
                level,
                maxHealth,
                maxLevel,
            }) =>
                ships.findOneAndUpdate(
                    {
                        name,
                    },
                    {
                        name,
                        cost,
                        class: _class,
                        description,
                        health,
                        levelRequired,
                        speed,
                        weapons,
                        level,
                        maxHealth,
                        maxLevel,
                    },
                    {
                        upsert: true,
                    }
                )
        )
    );
})();
